JNet/Models/Job.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JNet.Models
{
    public class Job
    {
        public int Id { get; set; }
        public string Title { get; set; }

        public Company Company { get; set; }
        public int CompanyId { get; set; }

        [Display(Name = "Post Date")]
        public DateTime PostDate { get; set; }
        
        [Display(Name = "Applied Date")]
        public DateTime AppliedDate { get; set; }

        public string Url { get; set; }
        public bool IsExpired { get; set; }

        public ApplicationUser User { get; set; }
        public string UserId { get; set; }
    }
}

JNet/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JNet.Models;
using JNet.Persistences;
using Microsoft.AspNet.Identity;

namespace JNet.Controllers
{
    [Authorize]
    public class JobsController : Controller
    {
        public JNetDbContext Context { get; }

        public JobsController()
        {
            Context = JNetDbContext.Create();
        }

        protected override void Dispose(bool disposing)
        {
            Context.Dispose();
            base.Dispose(disposing);
        }

        // GET: Job/New
        public ActionResult New()
        {
            return View();
        }

        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var result = Context.Jobs
                            .Include(x => x.Company)
                            .Include("Company.Location")
                            .Where(x => x.UserId == userId)
                            .ToList();
            return View(result);
        }

        [HttpPost]
        public ActionResult Create(Job model)
        {
            if (!ModelState.IsValid)
            {
                return View("New", model);
            }
            model.UserId = User.Identity.GetUserId();
            Context.Jobs.Add(model);
            Context.SaveChanges();
            ViewBag.Message = "Add";
            return View("New");
        }
    }
}

JNet/Views/Jobs/Index.cshtml
@model IEnumerable<JNet.Models.Job>

<h2>Jobs</h2>

<table class="table table-hover">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Company</th>
        <th scope="col">Location</th>
    </tr>
    </thead>
    <tbody>

    @{
        int row = 1;
        foreach (var j in @Model)
        {
            <tr>
                <th scope="row">@row</th>
                <td>@j.Title</td>
                <td>@j.Company.Name</td>
                <td>@j.Company.Location.City, @j.Company.Location.State</td>
            </tr>
            row++;
        }
    
    }

    </tbody>
</table> 

JNet/Views/Jobs/New.cshtml
@model JNet.Models.Job

@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Job</h2>
<br/><br/>
@using (Html.BeginForm("Create", "Jobs"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Title)
        @Html.TextBoxFor(m => m.Title, new {placeholder="Title", @class="form-control"})
        @Html.ValidationMessageFor(m => m.Title, "", new {@class="text-danger"})
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.PostDate)
        @Html.TextBoxFor(m => m.PostDate, new { placeholder = "Post Date", @class = "form-control" })
        @Html.ValidationMessageFor(m => m.PostDate, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.AppliedDate)
        @Html.TextBoxFor(m => m.AppliedDate, new { placeholder = "Applied Date", @class = "form-control" })
        @Html.ValidationMessageFor(m => m.AppliedDate, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Url)
        @Html.TextBoxFor(m => m.Url, new { placeholder = "Url", @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Url, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Company.Name)
        @Html.TextBoxFor(m => m.Company.Name, new { placeholder = "Company", @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Company.Name, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Company.Location.City)
        @Html.TextBoxFor(m => m.Company.Location.City, new { placeholder = "City", @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Company.Location.City, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Company.Location.State)
        @Html.TextBoxFor(m => m.Company.Location.State, new { placeholder = "State", @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Company.Location.State, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Company.Location.ZipCode)
        @Html.TextBoxFor(m => m.Company.Location.ZipCode, new { placeholder = "Zip Code", @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Company.Location.ZipCode, "", new { @class = "text-danger" })
    </div>
    <button class="btn btn-primary" type="submit">Save</button>
    <button class="btn btn-primary">Cancel</button>
}

@section scripts
{
    <script>
        $(document).ready(function () {
            if('@ViewBag.Message' === "Add")
                toastr.success('Success');
        });
    </script>
}